### ISSUE TITLE
Does not work in Xcode 7?

### ISSUE THREAD

**Issue by M4urice** [ryanmeisters/Xcode-Plugin-Open-Sublime-Text#14]
Can not use the plugin with Xcode Version 7.1 (7B91b). The menu option is not even visible.

**Comment by ryanmeisters** [comment]
Just released 1.4.2 which adds support for Xcode 7.1. Apologies for the delay. 

Alcatraz doesn't seem to be working for me in 7.1.. so you may need to clone this repo, open the xcodeproj, and hit run. This should install the plugin. After restarting Xcode, you should see the menu item!
