### ISSUE TITLE
Error building the project

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [ryanmeisters/Xcode-Plugin-Open-Sublime-Text#2]
I tried installing the plugin for Xcode 6.2 beta but the build fails with the below error.

![screen shot 2015-02-28 at 4 34 04 pm](https://cloud.githubusercontent.com/assets/2551877/6425970/ab7912f2-bf67-11e4-96bc-42de9d8542a9.png)

**Comment by ryanmeisters** [comment]
Hey Isuru. My apologies for not being available to help you out on this. We're all updated for Xcode 6 now with commit 604b012. An uninstall/reinstall with Alcatraz or build and copy to the plugins folder should sort you out. Let me know if you still have issues!

**Comment by Isuru-Nanayakkara** [comment]
It works now, Ryan. Thank you.
