### ISSUE TITLE
Xcode Crashing every time

### ISSUE THREAD

**Issue by satyananda** [ryanmeisters/Xcode-Plugin-Open-Sublime-Text#3]
My Xcode Crashed every time after installing this Plugin.

**Comment by ryanmeisters** [comment]
Cool. Does it crash on launch? Or only when you try to use the plugin? Do you have Sublime Text 3 installed? This plugin requires /Applications/Sublime\ Text.app to exist (the default install location for Sublime Text 3).

**Comment by satyananda** [comment]
when try to use it is happening. i haven't installed  Sublime Text 3. Thanks..

**Comment by ryanmeisters** [comment]
Hey satyananda, We added support for Sublime Text 2 a couple of days ago. You might try uninstalling the plugin and reinstalling the latest version. Let us know if you're still having issues

**Comment by satyananda** [comment]
thanks.
