### ISSUE TITLE
XCode6 support

### ISSUE THREAD

**Issue by kspes** [ryanmeisters/Xcode-Plugin-Open-Sublime-Text#5]
The plugin currently doesn't work with Xcode6. if installed with alcatraz it works at first, but on second launch it doesn't load.

xcode stderr gives this:
> PluginLoading: Required plug-in compatibility UUID A16FF353-8441-459E-A50C-B071F53F51B7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OpenInSublimeText.xcplugin' not present in DVTPlugInCompatibilityUUIDs

So, simply adding A16FF353-8441-459E-A50C-B071F53F51B7 to the project plist and rebuilding the plugin solves the problem.

I suggest fixing this and making another submission to alcatraz for future users.

Thanks for the plugin, I love it!

**Comment by changbiao** [comment]
#1 And my Xcode6.3(6D570) UUID is 9F75337B-21B4-4ADC-B558-F9CADF7073A7;
#2 Xcode IDEKit.h has changed；So I edit OSTUtil.h:
```
IDEWorkspaceWindowController* OSTLastActiveWindowController(){
    // TODO: Must update IDEKit.h for Xcode5
    static IDEWorkspaceWindowController* workspace = nil;
    if ([[IDEWorkspaceWindow class] respondsToSelector:@selector(lastActiveWorkspaceWindow)])
    {   //for Xcode6.3
        workspace = [IDEWorkspaceWindow performSelector:@selector(lastActiveWorkspaceWindow)];
    }
    else if([[IDEWorkspaceWindow class] respondsToSelector:@selector(lastActiveWorkspaceWindowController)])
    {
        workspace = [IDEWorkspaceWindow performSelector:@selector(lastActiveWorkspaceWindowController)];
    }
    NSLog(@"插件获取工作区控制器: %@", workspace);
    return workspace;
}
```

**Comment by ryanmeisters** [comment]
Thanks a lot guys. My apologies for not having this plugin updated sooner. Been swamped lately. Thanks for the help!
